#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)

var=$(hostname)
new_string="error_page 404 /custom_404.html;\n location /redirect_me {\n return 301 \$scheme://www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update package lists and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create index.html in default nginx directory
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null

# Create custom_404.html in custom directory
sudo mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Modify Nginx configuration file
sudo sed -i "s@^\s*location / {@$new_string@" /etc/nginx/sites-available/default
sudo sed -i "s@^\s*server {@$new_string2@" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart

