#!/usr/bin/env bash
# Installs and configures HAproxy in a load balancer server

# Check if the script is being run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Script must be run as root"
    exit 1
fi

# Install required packages
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.*

# Enable HAProxy
echo "ENABLED=1" >> /etc/default/haproxy

# Create HAProxy configuration file
mv /etc/haproxy/haproxy.cfg{,.original} || true
touch /etc/haproxy/haproxy.cfg

# Populate HAProxy configuration file
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 59637-web-01 54.160.85.72:80 check
    server 59637-web-02 35.175.132.106:80 check
EOF

# Start HAProxy service
service haproxy start

