#!/usr/bin/env bash
# Loops from one to ten and displays:
#   "bad luck" for the fourth iteration
#   "good luck" for the eigth iteration
#   "Best School" for all other iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
