#!/usr/bin/env bash
# Display numbers from one to twenty in addition to:
#   "bad luck from China" for the fourth iteration
#   "bad luck from Japan" for the nineth iteration
#   "bad luck from Italy" for the seventeenth loop iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
