#!/usr/bin/env bash
# Display the contents of the current directory in list format.
# Only displays the part of the name after the first dash. 

list=$(ls)
for k in $list; do
  echo "$k" | cut -d '-' -f2
done
